server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    resolver 127.0.0.11 valid=5s ipv6=off;

    set $auth_service auth:8083;
    set $offer_service offer:8080;
    set $availability_service availability:8081;
    set $booking_service booking:8082;

    location /auth-api/ {
        rewrite ^/auth-api/(.*)$ /$1 break;
        proxy_pass http://$auth_service;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /offer-api/ {
        rewrite ^/offer-api/(.*)$ /$1 break;
        proxy_pass http://$offer_service;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /availability-api/ {
        rewrite ^/availability-api/(.*)$ /$1 break;
        proxy_pass http://$availability_service;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /booking-api/ {
        rewrite ^/booking-api/(.*)$ /$1 break;
        proxy_pass http://$booking_service;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
