CREATE TABLE IF NOT EXISTS availability_slot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id BIGINT NOT NULL,
    starts_at TIMESTAMP NOT NULL,
    ends_at TIMESTAMP NOT NULL,
    capacity INTEGER NOT NULL,
    reserved_count INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(255) NOT NULL,
    CONSTRAINT chk_availability_slot_capacity_positive CHECK (capacity > 0),
    CONSTRAINT chk_availability_slot_reserved_count_non_negative CHECK (reserved_count >= 0),
    CONSTRAINT chk_availability_slot_reserved_count_within_capacity CHECK (reserved_count <= capacity),
    CONSTRAINT chk_availability_slot_time_order CHECK (ends_at > starts_at)
);

CREATE INDEX IF NOT EXISTS idx_availability_slot_offer_status_starts
    ON availability_slot (offer_id, status, starts_at);
