CREATE TABLE IF NOT EXISTS auth_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_auth_user_email UNIQUE (email),
    CONSTRAINT chk_auth_user_email_not_blank CHECK (length(trim(email)) > 0),
    CONSTRAINT chk_auth_user_display_name_not_blank CHECK (length(trim(display_name)) > 0),
    CONSTRAINT chk_auth_user_password_hash_not_blank CHECK (length(trim(password_hash)) > 0),
    CONSTRAINT chk_auth_user_role CHECK (role IN ('CUSTOMER', 'ADMIN')),
    CONSTRAINT chk_auth_user_status CHECK (status IN ('ACTIVE', 'DISABLED'))
);
