CREATE TABLE IF NOT EXISTS offer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    image_url VARCHAR(2048) NOT NULL,
    description VARCHAR(2048) NOT NULL,
    price NUMERIC(7, 2) NOT NULL,
    archived BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT chk_offer_price_positive CHECK (price > 0)
);

CREATE INDEX IF NOT EXISTS idx_offer_archived ON offer (archived);
